### ISSUE TITLE
Setting blind position (now?) also needs lamella to be set

### ISSUE THREAD

**Issue by OdyX** [siku2/hass-dingz#12]
From: https://github.com/siku2/hass-dingz/blob/a4af1f744ac2057a5b62fe1a3b319e3de9945850/custom_components/dingz/api.py#L721

This seems to be needed (at least)
```python
kwargs["lamella"] = 0
```
See https://www.dingz.ch/fr/configurer/playground-rest-api-114.html?_usehttp=true&ip=#apidoc-92

Without the `lamella` argument, dingz reports "400 Bad Request"

**Comment by siku2** [comment]
If that's all that's required, could you open up a PR with the changes?
I don't have any covers to test this anyway.
