### ISSUE TITLE
Complément d'information firmware 1.3.30

### ISSUE THREAD

**Issue by JiPi72** [siku2/hass-dingz#17]
![Capture d’écran 2023-02-11 à 15 08 33](https://user-images.githubusercontent.com/22003617/218263453-8f1d470f-86d4-4b77-a79b-b8c068bff35c.png)

Bonjour, avez-vous testez avec le nouveau firmware ?
Je ne vois que 4 entités et je ne vois pas les boutons.

Possible de m'aider ?

Merci, JP

**Comment by stevenrey** [comment]
Same issue here

**Comment by JiPi72** [comment]
> Même problème ici 

Pour information, il faut dans les (DIngz) nommé tout les butons y compris le Store
A ce moment , rafraîchir le service et tous les boutons vont arriver visible.

Le seul problème constaté, le retour d'information, après rafraîchissement manuel tout fonctionne et 2 min après plus rien !

**Comment by siku2** [comment]
This is no longer relevant as the newer FW version 2.0.0 is out and supported by the new version of this integration.
Btw, I do read French, but I prefer to keep my communication in English on here.
