### ISSUE TITLE
How to read inputs/buttons?

### ISSUE THREAD

**Issue by Ben-Kaniobi** [siku2/hass-dingz#21]
According to the Readme, inputs are supported. However I can only find entities for outputs, the LED, temperature sensor and motion sensor.

Do I have to configure something in the Dingz webinterface first?

**Comment by Vali6053** [comment]
I have the problem that it only shows me the sensors entities such as brightness and temperature.  The outputs such as lamps are not displayed to me.

**Comment by Ben-Kaniobi** [comment]
@Vali6053 what version of the Dingz Firmware are you using? After updating from v1.x.x to v2.0.21 most (or all?) entities aren't available anymore for me either...

**Comment by Vali6053** [comment]
My version is the v2.0.21.

**Comment by siku2** [comment]
@Ben-Kaniobi, @Vali6053, I finally got some time to update (actually, more like "rewrite") this integration.
Please give the new version a shot and let me know how it goes. The best time to fix things and add features is right now, while I still have time.

**Comment by Ben-Kaniobi** [comment]
@siku2 v0.4.2 works great! I can finally use Dingz again and it integrates much more nicely. Thanks for your work!

As for the inputs/buttons, I still can't find entries in the Dingz devices in HASS.

* In the Dingz App, I have one button named to "Bla" and have no action set (is this the problem?)
* In the web interface I can set more options for that button, but am not sure what to use if I only want it to trigger an automation in HASS (probably "Virtual" as it does not control any local light/thermostat)
* I tried a few settings and restarted HASS, but the Dingz device did not list a new entity

Can you give me some pointers how to get it working please?

**Comment by siku2** [comment]
Just saw that as well, will update this to avoid confusion. I'm also writing a guide on how to enable MQTT to make this process easier (should be done in a few minutes).

There is another option to enable this functionality through the "webhook" capabilities of the dingz, but I opted against implementing this as well, because MQTT is the superior approach for this sort of thing.
If you have a reason why you don't want to use MQTT, I'm happy to evaluate the other option as well.

**Comment by siku2** [comment]
@Ben-Kaniobi , I will mark this issue as closed, but please let me know how it goes once you set up the MQTT connection.

**Comment by Ben-Kaniobi** [comment]
@siku2 All right, I finally got around in enabling MQTT.

I set up the MQTT broker in docker on my NAS, not via the Home Assistant AddOn. I am running Home Assistant on a Raspberry Pi without SSD/HDD but SDCard only, so I'm trying to avoid anything that constantly writes to the drive there.
For setting up the broker in docker and connecting to Home Assistant, I used [this guide](https://www.homeautomationguy.io/blog/docker-tips/configuring-the-mosquitto-mqtt-docker-container-for-use-with-home-assistant). However it seems that the guide mixes up `/mosquitto` and `/opt/mosquitto` (?), so I used the former one everywhere and ignored the `opt` directory.

After that I followed the rest of your guide. Here are my notes regarding that:
* The Dingz were able to resolve the hostname of my NAS, I didn't need to use the IP address.
* The MQTT URI might also use the port number (I guess this even is required when not using the default port 1883)
* The MQTT Diagnostic didn't change to _Connected_ before reloading the device. After reloading, I worked and from then on always showed the current state immediatly (e.g. switched to _Disconnected_ when changing the URI to something invalid, and switched back to _Connected_ when correcting the URI again).
* It took me a short while to figure out how to use the new button events as triggers for an automation:
  * Using a _Manual event_ trigger with `event.dingzname_buttonname` didn't work (maybe I had a typo, but more likely that's for something else)
  * Using a _State_ trigger with the dingz button event for the **Entity**, _Event type_ for the **Attribute** and _p_ for the **To**, it worked.  
  The attribute values seem to be as follow:
    * p: pushed down
    * r: released
    * mX: pressed X times
    * h: (I have no idea, I didn't see this one, maybe it stands for "held down" and only shows up depending on how the button is configured in the dingz webinterface??)
    * &rarr; So, on a normal button press I would see p, followed by r and then m1.
