### ISSUE TITLE
Could not find Repository

### ISSUE THREAD

**Issue by chaoscrack** [siku2/hass-dingz#3]
Unfortunately I could not find the repository.

I tried with hass-dingz and dingz but there is no result of my search.

The version of my HACS is 1.15.2

Thanks for help
Patrick

**Comment by siku2** [comment]
Did you actually add the repository first? There's no "searching" for a custom repository, you need to manually add it using its URL.

**Comment by siku2** [comment]
Just realised that I never bothered to add detailed instructions to the README, apologies.
You need to add this repository as a "custom repository" before being able to download the integration.
Please refer to the official documentation for how to do that: <https://hacs.xyz/docs/faq/custom_repositories>

**Comment by siku2** [comment]
Also, just as a heads-up. This integration currently only supports the dingz API version 1.2. They made some breaking changes in 1.3 (for whatever reason...) and I haven't gotten around to updating this. However, I'm planning to do that within the next few days.
