### ISSUE TITLE
Problem at initialization

### ISSUE THREAD

**Issue by chaoscrack** [siku2/hass-dingz#36]
Unfortunately I have to setup a new HomeAssistant from new.
At my old HA I had the hass-dingz Version 0.2.0 and my dingz is on FW 1.3.30.
Now when I try to integrate my dingz I got an error at the initialization.
![Bildschirmfoto 2023-10-18 um 19 42 00](https://github.com/siku2/hass-dingz/assets/14803964/659f9bb4-9a46-47ec-9b3d-61a068791ef3)
I tried the Version 0.20, 0.3.1 and 0.4.2.

**Comment by siku2** [comment]
Please add the relevant debug logs.

**Comment by chaoscrack** [comment]
I did a new installation of HA. Now it works.

I have an other question.
I did a automation. If my shelly switch on, the LED at the dingz goes on. At teh automation I can change the brigtness but not the color. Is there an ohter way to change the color. If not I would be nice to have it with the next update of this tool.

Thanks!

**Comment by siku2** [comment]
Happy to hear that it's working now. As for your other issue I suspect there's an issue in the integration with the classification. Can you please elaborate on the details like describing your configuration (ideally with some screenshots) and what it should look like in HA?

**Comment by chaoscrack** [comment]
I try... :-)

Here is my simple automation:
![Bildschirmfoto 2023-12-27 um 14 55 59](https://github.com/siku2/hass-dingz/assets/14803964/6d11c666-8ab4-418f-b07e-9ed666d8a583)

At a push on the shelly, the LED from the Dingz turns on and I can choose the brightness of the LED. But the color I can't choose/change.
For me it would be nice to have a second field next below brightness for the color, or a separate action for the color.

**Comment by siku2** [comment]
You need to use the `light.turn_on` service instead of going through the device actions:
![image](https://github.com/siku2/hass-dingz/assets/16530283/66361260-186d-4290-ad10-ffeca9cef7dd)

that way you have access to all the color options.
I'm not sure why the color doesn't show up on the action menu.

**Comment by chaoscrack** [comment]
Thank you, that's exactly what I was looking for.
