### ISSUE TITLE
MQTT-Anmeldung funktioniert nicht ...

### ISSUE THREAD

**Issue by Luedem25** [siku2/hass-dingz#42]
Salü Alle

Als erstes, ein herzliches Dankeschön für das tolle Dingz-Plugin. Und, bin Neuling mit HASS. Suche eine Alternative zu Jarvis (ioBroker). Das GUI von HASS gefällt mir sehr gut.

**Technisches Umfeld**:
- ioBroker (Proxmox)
- Home-Matic IP (Raspberry-Matic): 3.71.12
- Shelly's
- Jarvis zur Visualisierung
- 10 Dingz (sehr schnelle Verbindung über MQTT zum ioBroker)
- Dingz-FW: 2.11
- Mosquitto-Broker-Plugin: 6.4.0
- Dingz Home Assistant Integration: 0.4.2

Irgendwie funktioniert die Verbindung (mqtt://dingz:dingz@192.168.1.23:1883) zwischen Dingz und HASS nicht. Ich glaube, dass ich alles nach Drehbuch eingerichtet habe. Die Verbindung ist mit dem "MQTT-Explorer" erfolgreich getestet.

Hat jemand eine Idee, wo der Fehler liegt?

Vielen Dank für die Unterstützung.

LG jean

**Comment by altery** [comment]
Same problem, I do see that Dingz connects to the MQTT broker and I also see data in the topics. But it looks like HA respectively this integration doesn't interpret the messages correctly. Also, the debug MQTT sensor shows 'disconnected'.

**Comment by siku2** [comment]
I guess I really need to add a note somewgere that the integration needs to be reloaded to connect to the broker.

The other point with the timestamp sensor is actually a bug that I hadn't noticed yet. I will take care of that asap

**Comment by siku2** [comment]
The timestamp issue has been fixed in 0.5.0
