### ISSUE TITLE
More then 4 Dingz not working

### ISSUE THREAD

**Issue by schmidi198** [siku2/hass-dingz#48]
When i want to add more then 4 Dingz devices i receive the message that the device is allreasy added. But it dies not show up. When i remove one of fhe 4 an add a new obe it shows up. Is there a limit of 4 devices?

**Comment by siku2** [comment]
This should only happen when, for whatever reason, multiple Dingz devices have the same id. There's no limit specifically for 4 devices.

Can you please enable debug logging for the integration and post the logs here? That should give me a clear picture of what's going on.

**Comment by schmidi198** [comment]
Your hint with the Id was key! I have done a copy of the configuration and uploadet this to all Dingz because all have the same config. I was not aware that the id is not unique in thr dingz config. Thank you for your advice.
