### ISSUE TITLE
Only LED was discovered

### ISSUE THREAD

**Issue by schmidi198** [siku2/hass-dingz#6]
I installed the version 0.1.5 via HACS in my Home Assistant. But the only entity was found is the LED, even that switch for the LED is not working. I've installed Home Assistant 2021.11.5. What I'm doing wrong?

**Comment by siku2** [comment]
Without further information there's not much I can do here.

**Comment by Zealand67** [comment]
I do have the same issue as Schmidi198.
The error log show a few errors:
Unexpected error fetching state data: 'target'
15:35:05 – (ERROR) dingz (custom integration) - message first occurred at 14:25:32 and shows up 752 times
failed to create `Blind` from JSON: {'moving': 'stop', 'position': 0, 'lamella': 0, 'readonly': False, 'index': {'relative': 0, 'absolute': 1}}
15:35:05 – (ERROR) dingz (custom integration) - message first occurred at 14:25:32 and shows up 752 times
Can't connect to ESPHome API for 192.168.0.107 @ 192.168.0.107: Timeout while connecting to ('192.168.0.107', 6053)
15:27:52 – (WARNING) /usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py
Empty reply found when expecting JSON data
15:05:19 – (WARNING) RESTful
Error fetching data: http://192.168.0.151/api/v1/state failed with
15:05:19 – (ERROR) RESTful
Update of sensor.dingz_test_state is taking over 10 seconds
15:05:18 – (WARNING) helpers/entity.py
